data:
  min_salary: 1000
  lower_percentile: 2
  upper_percentile: 98
  salary_scale: 0.001
  test_size: 0.2
  random_state: 42
features:
  cardinality:
    max_categories: 50
    min_frequency: 100
    other_category: Other
    drop_other_from:
    - Country
    - DevType
    - Industry
    - Age
    - ICorPM
    - OrgSize
    - Employment
  encoding:
    drop_first: true
model:
  n_estimators: 5000
  learning_rate: 0.023045198544870596
  max_depth: 4
  min_child_weight: 16
  random_state: 42
  n_jobs: -1
  early_stopping_rounds: 50
  subsample: 0.9979763430470896
  colsample_bytree: 0.7341672321169792
  reg_alpha: 0.10279490840973991
  reg_lambda: 1.9799853115073398
  gamma: 2.809228604965898
training:
  verbose: false
  save_model: true
  model_path: models/model.pkl
guardrails:
  max_mape_per_category: 100
  max_abs_pct_diff: 100
